# Generated by Django 5.1.4 on 2025-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(upload_to='catalog/', verbose_name='Изображение'),
        ),
    ]
