# Generated by Django 5.1.4 on 2025-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_flower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
